version: '3.1'

volumes:
  geonetwork:
  pgdata:
  pglog:
  esdata:
  nginxlog:

networks:
  gn-network:
    driver: bridge


services:
  www:
    image: nginx:1.22
    ports:
      - 80:80
    environment:
      # Only used for / redirect to default webapp
      - NGINX_PUBLIC_HOST=localhost
      #- NGINX_PUBLIC_HOST=apps.titellus.net
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./nginx:/etc/nginx/templates
      - nginxlog:/var/log/nginx
    depends_on:
      - geonetwork
    networks:
      - gn-network

  database:
    env_file:
      - .env
    image: postgis/postgis:11-2.5
    # environment:
    #   POSTGRES_USER: geonetwork
    #   POSTGRES_PASSWORD: geonetwork
    #   POSTGRES_DB: geonetwork4
    ports:
      - 5433:5432
    command: [ "postgres",
               "-c", "log_statement=all",
               "-c", "logging_collector=true",
               "-c", "log_file_mode=0644",
               "-c", "log_directory=/var/log/postgresql",
               "-c", "log_filename=postgresql.log" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglog:/var/log/postgresql
      - './postgis/init-scripts/1-init-dbs.sh:/docker-entrypoint-initdb.d/1-init-dbs.sh'
    networks:
      - gn-network

  geonetwork:
    build:
      context: .
    restart: always
    # ports:
    #   - 8080:8080
    environment:
      DATA_DIR: /catalogue-data

      JAVA_OPTS: >
        -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Dgeonetwork.resources.dir=/catalogue-data/resources
        -Dgeonetwork.data.dir=/catalogue-data
        -Dgeonetwork.codeList.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/codelist
        -Dgeonetwork.schema.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins

      ES_HOST: elasticsearch
      ES_PROTOCOL: http
      ES_PORT: 9200
      ES_USERNAME: elastic
      ES_PASSWORD: es_password

      KB_URL: http://kibana:5601

      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: database
      GEONETWORK_DB_PORT: 5432
      GEONETWORK_DB_NAME: geonetwork
      GEONETWORK_DB_USERNAME: geonetwork
      GEONETWORK_DB_PASSWORD: geonetwork

      # GEONETWORK_MICROSERVICESPROXY_TARGETURI: http://ogc-api-records-service:8080
    volumes:
      - geonetwork:/catalogue-data
    depends_on:
      - elasticsearch
      - database
    networks:
      - gn-network

  # ogc-api-records-service:
  #   image: geonetwork/gn-cloud-ogc-api-records-service:0.2.1
  #   platform: linux/amd64
  #   ports:
  #     - 9901:9901
  #   environment:
  #     SPRING_PROFILES_ACTIVE: standalone
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/geonetwork
  #     SPRING_DATASOURCE_USERNAME: geonetwork
  #     SPRING_DATASOURCE_PASSWORD: geonetwork
  #     GN_BASEURL: http://geonetwork:8080/geonetwork/api
  #     GN_LEGACY_URL: http://geonetwork:8080/geonetwork
  #     GN_INDEX_URL: http://elasticsearch:9200
  #     SERVER_FORWARDHEADERSSTRATEGY: FRAMEWORK

  #   depends_on:
  #     - database
  #     - elasticsearch
  #   networks:
  #     - gn-network

  elasticsearch:
    image: elasticsearch:7.11.1
    # ports:
    #   - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
      bootstrap.system_call_filter: 'false'
      # test auth with 'curl -u elastic:es_password localhost:9200'
      ELASTIC_PASSWORD: es_password
      ELASTIC_SECURITY: 'true'
      xpack.security.enabled: 'true'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - gn-network

  kibana:
    image: kibana:7.11.1
    ports:
      - 5601:5601
    environment:
     # for all options, see https://www.elastic.co/guide/en/kibana/current/settings.html
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      SERVER_BASEPATH: /geonetwork/dashboards
      SERVER_REWRITEBASEPATH: 'false'
      KIBANA_INDEX: .dashboards
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'true'
      # xpack.security.enabled: false
      # xpack.monitoring.enabled: false
      ELASTICSEARCH_PASSWORD: es_password
      ELASTICSEARCH_USERNAME: elastic
    networks:
      - gn-network
    depends_on:
      - elasticsearch
